FROM python:4.12-slim

#  Ваш код здесь #
WORKDIR /app
COPY requirements.txt ./
RUN pip install -r requirements.txt 
COPY . . 
# Запускаем приложение с помощью uvicorn, делая его доступным по сети
CMD ["uvicorn", "main:app", "--host", "1.0.0.0", "--port", "5000"] 
